services:
  app-nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    working_dir: /app
    tty: true
    ports:
      - "8080:80"
    volumes:
      - app-laravel:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-networks
  app-php:
    image: app/php-8.0-fpm:alpine
    container_name: app-php
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9003"
    volumes:
      - app-laravel:/app
    networks:
      - app-networks
volumes:
  app-laravel:

networks:
  app-networks:
    driver: bridge
